### ISSUE TITLE
'List' type converted to NULL

### ISSUE THREAD

**Issue by sebastien-de-saint-florent** [awslabs/emr-dynamodb-connector#1]
Hi,

I have a table that contains items with a List property. Something that would export in this format : 

```
{"id":{"s":"1234"}","values":{"l":[{"s":"one"},{"s":"two"}]}}
```

I'm trying to load the List as an array using hive. Whatever I try, "values" property always get converted to NULL in the result.

```
CREATE EXTERNAL TABLE items (id string, values array<string>)
STORED BY 'org.apache.hadoop.hive.dynamodb.DynamoDBStorageHandler'
TBLPROPERTIES ("dynamodb.table.name" = "myTable",
"dynamodb.column.mapping" = "id:id,values:values");
```

Is it something that is just not supported by the dynamodb-connector or am I doing something wrong?

Regards,

**Comment by astj** [comment]
I also encountered similar trouble.  I got `NULL` on parsing a List property of Binary data as `array<binary>`.

According to [AWS EMR release guide](http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/EMR_Interactive_Hive.html), Hive array can be mapped to "number set (NS), string set (SS), or binary set (BS)". Does it mean I cannot use List properties to import to Hive?

**Comment by itsgrimetime** [comment]
@sebastien-de-saint-florent @astj Thanks for bringing this to our attention, and we apologize for the latency in response. Just so you know, we are tracking this issue internally and hope to look at it in the near future. I'll be sure to update you here when we have more information.

**Comment by naataaniitsosie** [comment]
@itsgrimetime I'm politely asking for an update. Has this problem been addressed?

**Comment by 0xCafeDude** [comment]
I was facing the same problem while trying to use the connector with spark. I noticed that same information can be obtained by calling the getL api instead of the getSS api on AttributeValue

**Comment by itsgrimetime** [comment]
@sebastien-de-saint-florent @naataaniitsosie @astj @0xCafeDude sorry for taking so long to get to this. I've finally gotten some time to investigate and found that the connector assumes a List type is actually a StringSet, and that assumption gets propagated and causes the DynamoDBObjectInspector to receive the SS attribute (which is null) instead of the L attribute. I'm hoping to have a fix for this posted soon. Thanks again for your patience.

**Comment by itsgrimetime** [comment]
Oh - actually, I just realized #71 takes care of this, and adds additional types. I'll review that and see if we can't get it closed out.
