### ISSUE TITLE
DynamoDBClient MAX values.

### ISSUE THREAD

**Issue by SimoneCafiero** [awslabs/emr-dynamodb-connector#10]
Hi all,
I've read from the latest [DynamoDB API references](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html) that the _BatchWriteItem_ operation will be rejected if one of the following conditions is violated:

> - One or more tables specified in the BatchWriteItem request does not exist.
> - Primary key attributes specified on an item in the request do not match those in the corresponding table's primary key schema.
> - You try to perform multiple operations on the same item in the same BatchWriteItem request. For example, you cannot put and delete the same item in the same BatchWriteItem request.
> - There are more than 25 requests in the batch.
> - Any individual item in a batch exceeds 400 KB.
> - The total request size exceeds 16 MB.

Focusing on the following thresholds:

> - Any individual item in a batch exceeds 400 KB.
> - The total request size exceeds 16 MB.

And giving an eye to _org.apache.hadoop.dynamodb.DynamoDBClient_ class I can't figure out about which is the aim of the following (and in case is the individual item max size why is 512 instead of 400):

`private static final int MAX_ALLOWABLE_BYTE_SIZE = 512 * 1024;`

Also in _putBatch_ method (lines 182-188) the following check (third clause) on the write requests for a given table

`BatchWriteItemResult result = null;
    if (writeBatchMap.containsKey(tableName)) {
      if (writeBatchMap.get(tableName).size() >= batchLimit
          || (writeBatchMapSizeBytes + itemSizeBytes) > MAX_ALLOWABLE_BYTE_SIZE) {
        result = writeBatch(reporter, itemSizeBytes);
      }
    }`

uses the MAX_ALLOWABLE_BYTE_SIZE. Is that correct or should it be a different threshold (i.e. 16MB)?

If there's any documentation I can read where all details are defined and can be shared, it would be very appreciated.

Thanks for the support,
S.

**Comment by itsgrimetime** [comment]
Hi @SimoneCafiero, Thanks for letting us know about this - we're aware of the inconsistent size/items limits, and are currently working on fixing this. I'll close this issue once the commit has been merged in.
