### ISSUE TITLE
working with local dev instance of dynamoDB

### ISSUE THREAD

**Issue by huanchh** [awslabs/emr-dynamodb-connector#11]
we are evaluating how to read from local dev instance (not EMR) of dynamoDB into Spark, would this library support that or does it only work on EMR ?

**Comment by huanchh** [comment]
an update, I was getting a nulll pointer exception in ScanRecordReadRequest when interacting with local instance of DynamoDB at the line

result.getConsumedCapacity().getCapacityUnits()

but  result.getConsumedCapacity(). is null due to 

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html

after adding a null pointer check things seem to work

**Comment by itsgrimetime** [comment]
Hey @huanchh thanks for bringing this to our attention. I'm going to go ahead and make the fix you've recommended, and will close this issue once the commit gets merged in.

**Comment by SagarBhatia0105** [comment]
@huanchh Can I see a snippet of the code to see how you are interacting with local dynamodb from local spark cluster? I get the below exception when I try to do any query on my local instance:
18/09/05 17:06:41 WARN util.ClusterTopologyNodeCapacityProvider: Exception when trying to determine instance types
java.nio.file.NoSuchFileException: /mnt/var/lib/info/job-flow.json
