### ISSUE TITLE
Can't read Dynamo DB table data in RDD using Spark Scala.  Task 0.0 in stage 2.0 (TID 2) had a not serializable result: org.apache.hadoop.io.Text

### ISSUE THREAD

**Issue by venkatwilliams** [awslabs/emr-dynamodb-connector#116]
I trying to read read the data from Dynamo DB Table. 
`spark-shell --jars emr-dynamodb-hadoop-4.8.0.jar

import org.apache.hadoop.io.Text;
import org.apache.hadoop.dynamodb.DynamoDBItemWritable
import org.apache.hadoop.dynamodb.read.DynamoDBInputFormat
import org.apache.hadoop.dynamodb.write.DynamoDBOutputFormat
import org.apache.hadoop.mapred.JobConf
import org.apache.hadoop.io.LongWritable

var jobConf = new JobConf(sc.hadoopConfiguration)
jobConf.set("dynamodb.input.tableName", "sample")

jobConf.set("mapred.output.format.class", "org.apache.hadoop.dynamodb.write.DynamoDBOutputFormat")
jobConf.set("mapred.input.format.class", "org.apache.hadoop.dynamodb.read.DynamoDBInputFormat")

var sampleRDD = sc.hadoopRDD(jobConf, classOf[DynamoDBInputFormat], classOf[Text], classOf[DynamoDBItemWritable])`

sampleRDD.count() is working fine. 

sampleRDD.first() giving not serializable result exception. 

ERROR Details:
`scala> sample.first()
19/09/19 07:10:00 ERROR TaskSetManager: Task 0.0 in stage 2.0 (TID 2) had a not serializable result: org.apache.hadoop.io.Text
Serialization stack:
        - object not serializable (class: org.apache.hadoop.io.Text, value: )
        - field (class: scala.Tuple2, name: _1, type: class java.lang.Object)
        - object (class scala.Tuple2, (,{"guid":{"s":"1"},"Field1":{"s":"123"}}))
        - element of array (index: 0)
        - array (class [Lscala.Tuple2;, size 1); not retrying
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0.0 in stage 2.0 (TID 2) had a not serializable result: org.apache.hadoop.io.Text
Serialization stack:
        - object not serializable (class: org.apache.hadoop.io.Text, value: )
        - field (class: scala.Tuple2, name: _1, type: class java.lang.Object)
        - object (class scala.Tuple2, (,{"guid":{"s":"1"},"Field1":{"s":"123"}}))
        - element of array (index: 0)
        - array (class [Lscala.Tuple2;, size 1)
  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:2041)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2029)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2028)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
`
Anyone could resolve this issue. Please share your inputs if I am missing something.

**Comment by foscraig** [comment]
Text is not serializable so you need to convert those to something else. E.g. 
`val c=sampleRDD.map{ case(text) => (text.toString)}.collect()` as from [here](http://apache-spark-user-list.1001560.n3.nabble.com/How-to-solve-java-io-NotSerializableException-org-apache-hadoop-io-Text-td2650.html).
