### ISSUE TITLE
Releases not published on maven central

### ISSUE THREAD

**Issue by anilkumarmyla** [awslabs/emr-dynamodb-connector#122]
The latest version as per https://mvnrepository.com/artifact/com.amazon.emr/emr-dynamodb-tools is 4.12.0, while the commit history on this repo shows 4.13.0, 4.14.0 as already released

Is there a different repository that these releases are published?

**Comment by yuxiaorun** [comment]
I also have the same request, I have the cross account access issue which was resolved in 4.13.0, but 4.13.0 was not published on maven central yet. Please publish it since it will greatly affect my work.

**Comment by mazenmelouk** [comment]
And now I have the same request for 4.14.0 !

**Comment by kiritnimdia** [comment]
One more request for 4.14.0.

**Comment by anilkumarmyla** [comment]
released!
