### ISSUE TITLE
WCU calculation is broken if GSI is enabled in Tez hive

### ISSUE THREAD

**Issue by sivankumar86** [awslabs/emr-dynamodb-connector#129]
Create a table with 2 GSI and use Hive to import data from s3 using Tez.

set dynamodb.throughput.write.percent=1.0;

But, Job doesnot consume more than 50% of table capacity

**Comment by sivankumar86** [comment]
EMR 5.30

**Comment by PoeppingT** [comment]
Closing this as an apparently duplicate of https://github.com/awslabs/emr-dynamodb-connector/pull/130
