### ISSUE TITLE
Cannot get work with pyspark

### ISSUE THREAD

**Issue by senseysensor** [awslabs/emr-dynamodb-connector#13]
Currently I have no luck how to get things work. My following code fails:

    pyspark --jars /usr/share/aws/emr/ddb/lib/emr-ddb-hadoop.jar
    conf = {
        "dynamodb.servicename": "dynamodb",
        "dynamodb.input.tableName": "users",
        "dynamodb.endpoint": "https://dynamodb.eu-central-1.amazonaws.com",
        "dynamodb.regionid": "eu-central-1",
        "mapred.output.format.class": "org.apache.hadoop.dynamodb.write.DynamoDBOutputFormat",
        "mapred.input.format.class": "org.apache.hadoop.dynamodb.read.DynamoDBInputFormat"
    }
    sc.hadoopRDD(
        inputFormatClass='org.apache.hadoop.dynamodb.read.DynamoDBInputFormat',
        keyClass='org.apache.hadoop.io.Text',
        valueClass='org.apache.hadoop.dynamodb.DynamoDBItemWritable',
        conf=conf
    )

Shortly, I get following error:

    Job aborted due to stage failure: Task 0.0 in stage 0.0 (TID 0) had a not serializable result: org.apache.hadoop.dynamodb.DynamoDBItemWritable

Full traceback you may see [here](https://gist.github.com/senseysensor/a8158687a48b676685c04c8d22afed73).

I try do this in EMR, not locally.

**Comment by mbertrand** [comment]
I'm having the same problem, wondering if PySpark and emr-dynamodb-connector just aren't compatible right now, or is there a workaround?

**Comment by PoeppingT** [comment]
Hi there,

Thanks for letting us know. After a bit of investigation, it looks like this is because DynamoDBItemWritable doesn't implement Serializable, even though the underlying Serializer used by Spark expects it to. We're working on this issue internally, I'll update when we have a date for a fix.

By the way, in the future, you can get a better log if you look at the yarn logs for the application. The way I was doing it was this:
yarn application -list -appStates ALL (find the one you ran that failed)
yarn logs -applicationId <applicationId> > ~/<applicationId>.log

Then you can view that log, in addition to just the output dropped to console in pyspark shell.

**Comment by Kuntal-G** [comment]
I'm not able to save the RDD to DynamoDB using Pyspark.

EMR 5.10

pyspark --jars /usr/share/aws/emr/ddb/lib/emr-ddb-hadoop.jar


For me, I'm able to read the Dynamodb data using the below code:

conf = {
    "dynamodb.servicename": "dynamodb",
    "dynamodb.input.tableName": "TestSpark",
    "dynamodb.output.tableName": "TestSpark2",
    "dynamodb.endpoint": "https://dynamodb.us-east-1.amazonaws.com",
    "dynamodb.regionid": "us-east-1",
    "mapred.output.format.class": "org.apache.hadoop.dynamodb.write.DynamoDBOutputFormat",
    "mapred.input.format.class": "org.apache.hadoop.dynamodb.read.DynamoDBInputFormat"
}

dynamoRDD = sc.hadoopRDD(
    inputFormatClass='org.apache.hadoop.dynamodb.read.DynamoDBInputFormat',
    keyClass='org.apache.hadoop.io.Text',
    valueClass='org.apache.hadoop.dynamodb.DynamoDBItemWritable',
    conf=conf
)
//Now the count or first method works well on the above RDD- dynamoRDD
dynamoRDD.count()

//But if I'm trying to save the RDD it is failing:

dynamoRDD.saveAsHadoopDataset(conf)


Error:

java.lang.ClassCastException: org.apache.hadoop.io.MapWritable cannot be cast to org.apache.hadoop.dynamodb.DynamoDBItemWritable


//Error is self-explanatory.. Im basically trying to read from one table and copy to another table as defined in the conf dictionary. I have even tried with separate conf (like inputConf, outputConf). But still getting the same error.

Whereas exactly same code is working fine with Scala.

**** So it seems to be an issue with the emr connector with Pyspark. Could you please look into the matter.

Why the input format type is changing to MapWritable while loading the data, whereas it is staying same as ynamoDBItemWritable in case of scala (spark-shell) ??
