### ISSUE TITLE
Runtime error NoSuchMethodError: org.apache.http.params.HttpConnectionParams

### ISSUE THREAD

**Issue by hemantborole** [awslabs/emr-dynamodb-connector#16]
Probably missing some dependency in the pom, or I am missing something in my class path during execution.
I see the above error (in the subject), when I execute the dynamodbimport class.
I tried passing httpcomponents-core(deprecated per doc) in the classpath, but that did not help.
I am going to debug this further, but if there is something obvious that I am missing, would like to be pointed out.

**Comment by PoeppingT** [comment]
How exactly are you trying to execute the class? Unfortunately it's not easy to help or take a bug report without reproduction steps.

**Comment by itsgrimetime** [comment]
This was fixed by #21
