### ISSUE TITLE
DynamoDb Spark example - emr-ddb-hadoop.jar does not exist

### ISSUE THREAD

**Issue by joemeszaros** [awslabs/emr-dynamodb-connector#18]
# Description

With the latest version of Amazon EMR (5.4) the jar file (`/usr/share/aws/emr/ddb/lib/emr-ddb-hadoop.jar`) referenced in the Spark section of README file does not exist.

It is already mentioned in the following [Big data blog post](https://aws.amazon.com/blogs/big-data/analyze-your-data-on-amazon-dynamodb-with-apache-spark/)

You have to manually build and copy the jar file to the master node, which is OK, but the documentation should be up to date.

**Comment by z-york** [comment]
Thanks for pointing this out @joemeszaros. We will get this fixed ASAP.

**Comment by joemeszaros** [comment]
Please also note, that the referenced maven dependency is invalid:

```
<dependency>
  <groupId>com.amazon.emr</groupId>
  <artifactId>emr-dynamodb-hadoop</artifactId>
  <version>4.1.0</version>
</dependency>
```
because version `4.1.0` does not exist in maven central (use `4.2.0` instead).

**Comment by z-york** [comment]
Thanks! I will fix that.

**Comment by z-york** [comment]
https://github.com/awslabs/emr-dynamodb-connector/pull/20 to fix the maven dependency
