### ISSUE TITLE
5.x releases may not have been published as of March 2024

### ISSUE THREAD

**Issue by yegeniy** [awslabs/emr-dynamodb-connector#193]
Hello, similar to issue #177, it seems that none of the 5.x versions are available on https://oss.sonatype.org/#nexus-search;quick~emr-dynamodb-connector yet

The latest seems to be 4.16.0

<img width="440" alt="image" src="https://github.com/awslabs/emr-dynamodb-connector/assets/292802/79b973c1-6518-4ee6-a75f-60a9ff27c424">

**Comment by akitanaka** [comment]
Deployed emr-dynamodb-connector jars to Maven Central.
