### ISSUE TITLE
Support for custom dynamo db regions

### ISSUE THREAD

**Issue by btrajkovski** [awslabs/emr-dynamodb-connector#31]
Currently emr-dynamodb-connector does not support setting a different region for dynamo DB tables. I have a scenario where tables are  located in one region and because that region does not support EMR clusters, EMR is located in another regions. 

It would really help if I can define dynamo DB region as custom argument for dynamodb export script and is there any specific reason why this is not implemented that I am missing?

**Comment by itsgrimetime** [comment]
Hi @btrajkovski, have you tried setting different configuration values like dynamodb.region and dynamo.regionid? Setting these will allow the connector to resolve the DynamoDB endpoint correctly, and ideally should allow you to access tables in different regions.

You can set these values in /etc/hadoop/conf/core-site.xml

**Comment by sivankumar86** [comment]
@btrajkovski you can pass region in table property,example 

 CREATE EXTERNAL TABLE testreg(user_id string) STORED BY 'org.apache.hadoop.hive.dynamodb.DynamoDBStorageHandler'  TBLPROPERTIES ( "dynamodb.table.name" = "testreg","dynamodb.column.mapping"="user_id:user_id","dynamodb.region"="us-west-2") ;

**Comment by ajay25** [comment]
@btrajkovski: Can you confirm if the above suggestions resolve your issue?

**Comment by btrajkovski** [comment]
@ajay25 Unfortunately no, and we moved on to alternative solutions. 

Let me give you a bit more background about the whole problem:
I was following this guide on how to setup automated backup of dynamodb data
https://aws.amazon.com/premiumsupport/knowledge-center/concurrent-emr-jobs-data-pipeline/
And in this guide DynamoDbExport and DynamoDbImport classes are being used and program arguments can be passed. 
The problem I had was I was unable to pass dynamodb region as argument and I don't have access to hadoop server directly as suggested by @itsgrimetime or tables.  So I think that using a dynamoDB table region as an optional argument is valid scenario.

**Comment by sivankumar86** [comment]
@btrajkovski, you have to pass region as argument  like -Ddynamodb.region=us-west-2  to override the default value if it is a map reduce program.

**Comment by itsgrimetime** [comment]
@btrajkovski were you able to try @sivankumar86's suggestion?

**Comment by itsgrimetime** [comment]
closing this since we haven't heard back from @btrajkovski
