### ISSUE TITLE
Could not find or load main class org.apache.hadoop.dynamodb.tools.DynamoDBExport

### ISSUE THREAD

**Issue by zhangzimou** [awslabs/emr-dynamodb-connector#32]
When I use export usage:

<code>
java -cp target/emr-dynamodb-tools-4.2.0-SNAPSHOT.jar org.apache.hadoop.dynamodb.tools.DynamoDBExport /where/output/should/go my-dynamo-table-name
</code>

there is an error:
<code>
Error: Could not find or load main class org.apache.hadoop.dynamodb.tools.DynamoDBExport
</code>

I can find this class in target/classes/org/apache/hadoop/dynamodb/tools/DynamoDBExport.class.
Can someone tell me how to fix this error? Thanks.

**Comment by sivankumar86** [comment]
@zhangzimou  Add all dependency jars in class path or if you have EMR cluster, run below command on master node.
hadoop jar emr-dynamodb-tools-4.4.0-SNAPSHOT.jar org.apache.hadoop.dynamodb.tools.DynamoDBExport <path> <tablename>

**Comment by ajay25** [comment]
I have confirmed this on EMR cluster. 
hadoop jar emr-dynamodb-tools/target/emr-dynamodb-tools-4.5.0-SNAPSHOT.jar org.apache.hadoop.dynamodb.tools.DynamoDBExport <path> <tablename>

This works and I don't see the class error. So, make sure the classpath is updated correctly.

**Comment by itsgrimetime** [comment]
@zhangzimou Can you confirm if the suggestion from @ajay25 worked for you?

**Comment by zhangzimou** [comment]
Yes, it worked.

**Comment by itsgrimetime** [comment]
@zhangzimou great, thanks.
