### ISSUE TITLE
Doesn't support DynamoDB boolean or map data types?

### ISSUE THREAD

**Issue by mattklein** [awslabs/emr-dynamodb-connector#33]
Any timeline for support of boolean or map data types?

**Comment by sivankumar86** [comment]
@mattklein I have added boolean support in hive connector . you can pull the code from  here https://github.com/awsbigdata/emr-dynamodb-connector and also, I have updated pull request for review.

**Comment by mattklein** [comment]
Thanks! Lacking support for boolean was a pain point, but the main obstacle to my use of this connector is the fact that it doesn't query on the DDB table primary key or secondary index, but rather always performs full table scans. I've opened a separate issue (and posts to the AWS Forums) about that.

**Comment by ranguEV3** [comment]
Closing. Let us know if you have any more concerns.
