### ISSUE TITLE
Connector doesn't use DDB primary key, always performs full table scan

### ISSUE THREAD

**Issue by mattklein** [awslabs/emr-dynamodb-connector#39]
I've tried using this connector to write a Hive query against a DynamoDB table that's defined with a partition key and a sort key. Even when my Hive query includes conditions on both the partition key and the sort key, the connector performs a full table scan to DynamoDB, rather than a query based on its primary key! My table has billions of items so this makes using the connector infeasible.

This posting sure seems to indicate that the connector *used to* be smart enough to use DDB indexes -- could this have gotten broken somewhere along the line?
http://hipsterdevblog.com/blog/2015/05/30/analysing-dynamodb-index-usage-in-hive-queries/

Related posts on AWS Forums:
https://forums.aws.amazon.com/thread.jspa?threadID=260026
https://forums.aws.amazon.com/thread.jspa?messageID=795525

**Comment by ajay25** [comment]
Can you confirm the EMR release label/ Connector version that you are using? 

I have fixed a similar bug where a simple query with a predicate using connector causes a scan. 

This is the commit- https://github.com/awslabs/emr-dynamodb-connector/commit/2ea294cd8067cfa1cd... 
which fixes the operators. 

Let us know if this fixes your issue.
