### ISSUE TITLE
Release new version with aws-java-sdk 1.11.*

### ISSUE THREAD

**Issue by miracodezu** [awslabs/emr-dynamodb-connector#42]
It looks like you have versions higher than 4.2.0 that have the updated aws-java-sdk version.  When is the next release planned? I'd rather use an updated release than revert other code that uses the newer SDK.

**Comment by ranguEV3** [comment]
New EMR release will come out at end of September or early October.
emr-5.6.0 should be using emr-dynamodb-connector 4.3.0

**Comment by itsgrimetime** [comment]
Latest EMR release (EMR 5.8.0) ships with emr-dynamodb-connector 4.4.0, so the latest SDK is available there.
