### ISSUE TITLE
connect to dynamo db local

### ISSUE THREAD

**Issue by mrigankt** [awslabs/emr-dynamodb-connector#43]
I need to connect to dynamo db local for which i need to set end point url . where i can do that .

**Comment by itsgrimetime** [comment]
Hi @mrigankt, have you tried setting the ["dynamodb.endpoint"](https://github.com/awslabs/emr-dynamodb-connector/blob/a9c657beadc2a7373fd02bc95e2c6ef94d0491e5/emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBConstants.java#L37) property?

**Comment by mrigankt** [comment]
where can i find this setting ?

**Comment by itsgrimetime** [comment]
You can just pass `-Ddynamodb.endpoint=<your endpoint>` as an argument.

**Comment by mrigankt** [comment]
thank you

**Comment by mrigankt** [comment]
now my template is working but now the issue is  that when  i mention dynamodb stream number i template.yml then it should trigger via following command 
aws --endpoint-url=http://172.16.123.1:8000 dynamodb put-item     --table-name BarkTable     --item Username={S="Jane Doe"},Timestamp={S="2016-11-18:14:32:17"},Message={S="Testing...1...2...3"}

but is not . to trigger it i have to run 
sam local generate-event dynamodb | sam local invoke

below is my index.js . can you tell us how to do it my way 


'use strict';
var AWS = require("aws-sdk");
AWS.config.update({
  region: "us-east-1",
  endpoint: "http://172.16.123.1:8000"
});

var dynamodb = new AWS.DynamoDB.DocumentClient();

exports.handler = (event, context, callback) => {

    event.Records.forEach((record) => {
        console.log('Stream record: ', JSON.stringify(record, null, 2));

        if (record.eventName == 'INSERT') {
           var params = {
                Item: {
                        date: Date.now(),
                        message: "Hello how are you"
                },

               TableName: 'guestbook'
        };

       dynamodb.put(params, function(err, data){
                if(err){
                        callback(err, null);
                        }else{
                        callback(null, data);
                        }
                });
        }
    });
    callback(null, `Successfully processed ${event.Records.length} records.`);
};

**Comment by itsgrimetime** [comment]
If your original issue is solved, I'm going to close close this one out. Will you open a new one for this new issue? Please add more details to that, too, when you do. I'm unfamiliar with the `sam` utility, and am having a hard time following what you are trying to do.

**Comment by mrigankt** [comment]
wrong blog u can close it
