### ISSUE TITLE
Problem with connection to DynamoDB

### ISSUE THREAD

**Issue by dchalupnik** [awslabs/emr-dynamodb-connector#45]
I have a problem while trying to use DynamoDBStorageHandler to collect partial data from DynamoDB.

I am using the newest EMR version with hive, EMR roles have full access to DynamoDb in IAM.
EMR is in the same region as DynamoDb table. NetworkACL allows all the necessary traffic. Security groups are set to public. I also pass dynamodb.endpoint, dynamodb.region, fs.s3a.access.key, fs.s3a.secret.key, dynamodb.regionid to hive-site.xml and core-site.xml.

I checked documentation many times, tried numerous configurations and despite all of my effort I still have the same result every time:

FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. java.lang.RuntimeException: Could not lookup table test_input in DynamoDB.

But this table exists. When I run aws(cli) configure on EMR master and pass credentials I can list it.
Also when I run Wireshark and use Hive with DynamoDBStorageHandler there is no connection to any DynamoDB endpoints.

Do you have any idea why it is not working? Some bug? Lack of documentaiton?
Bellow is the code that I'm running:

CREATE EXTERNAL TABLE raw_data (id bigint)
STORED BY 'org.apache.hadoop.hive.dynamodb.DynamoDBStorageHandler'
TBLPROPERTIES (
  "dynamodb.table.name" = "test_input",
  "dynamodb.region"="eu-central-1",
  "dynamodb.column.mapping" = "id:id"
);

**Comment by itsgrimetime** [comment]
Do you have the full stacktrace?

**Comment by dchalupnik** [comment]
Ok, I resolved it by adding:

```
<property>
  <name>fs.s3.awsAccessKeyId</name>
  <value>KEY</value>
</property>
<property>
  <name>fs.s3.awsSecretAccessKey</name>
  <value>SECRETKEY</value>
</property>
```

to core-site.xml, tez-site.xml and rollback to EMR 5.3

**Comment by itsgrimetime** [comment]
@dchalupnik you shouldn't have had to rollback to an earlier EMR release. Also, only adding those properties to core-site.xml should have been sufficient. I'm going to close this out as you seem to have unblocked yourself, but if there really is a bug that is preventing newer versions of EMR from working correctly here we would like to know - so feel free to re-open this.

**Comment by navsie** [comment]
@itsgrimetime   I am using EMR 5.3.1 and I face the same issue. I tried @dchalupnik solution but still did not solve my issue.
Error I get:
Logging initialized using configuration in file:/etc/hive/conf.dist/hive-log4j2.properties Async: true
hive> CREATE EXTERNAL TABLE hive_test_table (col1 string, col2 string, col3 string)
    > STORED BY 'org.apache.hadoop.hive.dynamodb.DynamoDBStorageHandler'
    > TBLPROPERTIES ("dynamodb.table.name" = "hive_test_table",
    > "dynamodb.column.mapping" = "col1:id,col2:creation_date,col3:last_update_time");
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. java.lang.RuntimeException: Could not lookup table hive_test_table in DynamoDB.
hive>
