### ISSUE TITLE
NullPointerException at AbstractDynamoDBRecordWriter (115) 

### ISSUE THREAD

**Issue by mharkins-spokeo** [awslabs/emr-dynamodb-connector#48]
As far as I know, this only applies to the downloadable, local version of DynamoDB, which apparently doesn't return "consumed capacity" even if it's requested.  Looping over it without null checking causes a NullPointerException.

Here's the line:
```java
for (ConsumedCapacity consumedCapacity : result.getConsumedCapacity()) {
```

**Comment by rentaow** [comment]
@mharkins-spokeo would you like to submit a pull request for this npe fix? If you do we'll take a look when possible.

**Comment by mharkins-spokeo** [comment]
@rentaow I could try to get one together.  What branch do you want it based on?  Any style preferences I should be aware of?

**Comment by rentaow** [comment]
Against master branch. There's a checkstyle plugin enabled in the package using google_checks. It should be fine if it doesn't complain about the changes.

**Comment by z-york** [comment]
#49 merged, closing this issue.
