### ISSUE TITLE
[ENHANCEMENT REQUEST] Connector doesn't support deleting records from the table

### ISSUE THREAD

**Issue by 0xCafeDude** [awslabs/emr-dynamodb-connector#70]
The connector has no way of specifying that a records needs to be deleted rather than saved or updated.

**Comment by Tang8330** [comment]
+1

**Comment by Tang8330** [comment]
@itsgrimetime I tried to modify source to be something like this: https://github.com/Tang8330/emr-dynamodb-connector/blob/dynamo4.2/emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBClient.java#L151

However, it's not quite working and is still inserting, despite me playing around with the default state.

Any ideas? I'm happy to make the necessary changes.

**Comment by Tang8330** [comment]
my function looks something like this:
```java
JobConf jobConf = new JobConf(sc.hadoopConfiguration());
jobConf.set(DynamoDBConstants.INPUT_TABLE_NAME, INPUT_TABLE_NAME);
jobConf.set(DynamoDBConstants.OUTPUT_TABLE_NAME, OUTPUT_TABLE_NAME);
jobConf.set(DynamoDBConstants.DELETION_MODE, "true");
filtered_results.saveAsHadoopDataset(jobConf);
```

**Comment by ajay25** [comment]
@Tang8330 Did you ensure that writeBatch()- https://github.com/awslabs/emr-dynamodb-connector/blob/master/emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBClient.java#L202 was indeed invoked?
1. I would suggest adding necessary logging in putBatch to understand what is going on?
2. Also, examine batchwriteresult. Specifically check for itemcollectionmetrics https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html#API_BatchWriteItem_ResponseSyntax to see how many records were affected.

**Comment by taklwu** [comment]
merge as #96

**Comment by tuppimax** [comment]
Hi Is there any documentation on how to use this with HIVE ?

**Comment by satya-thirumani** [comment]
Hi,

Is there any documentation on how to use this on EMR with HIVE ?
