### ISSUE TITLE
"incorrect" exception is thrown when bad mapping is used

### ISSUE THREAD

**Issue by gdoron** [awslabs/emr-dynamodb-connector#74]
For example, if in the following code you will remove cpc from the `CREATE EXTERNAL TABLE `  mapping, the following exception will br thrown
```
CREATE EXTERNAL TABLE ddb_cross_keywords_volumes
( keyword_key string,
  cpc bigint,
  volumes string)
STORED BY 'org.apache.hadoop.hive.dynamodb.DynamoDBStorageHandler'
TBLPROPERTIES(
 "dynamodb.table.name" = "cross_keywords_volumes_${hiveconf:partition_date}",
 "dynamodb.column.mapping"="keyword_key:keyword_key,volumes:volumes,cpc:cpc"
);

INSERT OVERWRITE TABLE ddb_cross_keywords_volumes
SELECT    concat(v.keyword, '_', CAST(v.country AS VARCHAR(5))) AS keyword_key,
          MAX(c.cpc) AS cpc,
          to_json(str_to_map(concat_ws(',', collect_set(v.month ||':'|| v.volume)), ',', ':')) AS volumes
FROM      sw_published_adwords.keywords_volumes__${hiveconf:pdl_branch} AS v
LEFT JOIN sw_published_adwords.keywords_cpcs__${hiveconf:pdl_branch} AS c
    ON  c.keyword = v.keyword
    AND c.country = v.country
    AND c.`date` >= '${hiveconf:from_date}'
    AND c.`date` <= '${hiveconf:to_date}'
WHERE     v.`date` >= '${hiveconf:from_date}'
AND       v.`date` <= '${hiveconf:to_date}'
GROUP BY  v.keyword, v.country;
```
> 
> 
> TaskAttempt 2 failed, info=[Error: Error while running task ( failure ) : attempt_1530441053089_0001_2_03_000072_2:java.lang.RuntimeException: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row (tag=0) {"key":{"_col0":"!4rc4n01d! 4: kohbeep edition astats","_col1":999},"value":{"_col0":null,"_col1":["2018-04:-1","2017-08:-1","2017-07:-1","2018-03:-1","2018-02:-1","2017-12:-1","2018-01:-1","2017-11:-1","2017-10:-1","2017-05:-1","2017-06:-1","2017-09:-1"]}}
>         at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.initializeAndRunProcessor(TezProcessor.java:211)
>         at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.run(TezProcessor.java:168)
>         at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:370)
>         at org.apache.tez.runtime.task.TaskRunner2Callable$1.run(TaskRunner2Callable.java:73)
>         at org.apache.tez.runtime.task.TaskRunner2Callable$1.run(TaskRunner2Callable.java:61)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at javax.security.auth.Subject.doAs(Subject.java:422)
>         at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
>         at org.apache.tez.runtime.task.TaskRunner2Callable.callInternal(TaskRunner2Callable.java:61)
>         at org.apache.tez.runtime.task.TaskRunner2Callable.callInternal(TaskRunner2Callable.java:37)
>         at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row (tag=0) {"key":{"_col0":"!4rc4n01d! 4: kohbeep edition astats","_col1":999},"value":{"_col0":null,"_col1":["2018-04:-1","2017-08:-1","2017-07:-1","2018-03:-1","2018-02:-1","2017-12:-1","2018-01:-1","2017-11:-1","2017-10:-1","2017-05:-1","2017-06:-1","2017-09:-1"]}}
>         at org.apache.hadoop.hive.ql.exec.tez.ReduceRecordSource.pushRecord(ReduceRecordSource.java:297)
>         at org.apache.hadoop.hive.ql.exec.tez.ReduceRecordProcessor.run(ReduceRecordProcessor.java:317)
>         at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.initializeAndRunProcessor(TezProcessor.java:185)
>         ... 14 more
> Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row (tag=0) {"key":{"_col0":"!4rc4n01d! 4: kohbeep edition astats","_col1":999},"value":{"_col0":null,"_col1":["2018-04:-1","2017-08:-1","2017-07:-1","2018-03:-1","2018-02:-1","2017-12:-1","2018-01:-1","2017-11:-1","2017-10:-1","2017-05:-1","2017-06:-1","2017-09:-1"]}}
>         at org.apache.hadoop.hive.ql.exec.tez.ReduceRecordSource$GroupIterator.next(ReduceRecordSource.java:365)
>         at org.apache.hadoop.hive.ql.exec.tez.ReduceRecordSource.pushRecord(ReduceRecordSource.java:287)
>         ... 16 more
> Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.NullPointerException
>         at org.apache.hadoop.hive.ql.exec.GroupByOperator.process(GroupByOperator.java:792)
>         at org.apache.hadoop.hive.ql.exec.tez.ReduceRecordSource$GroupIterator.next(ReduceRecordSource.java:356)
>         ... 17 more
> Caused by: java.lang.NullPointerException
>         at org.apache.hadoop.dynamodb.DynamoDBUtil.getItemSizeBytes(DynamoDBUtil.java:148)
>         at org.apache.hadoop.dynamodb.DynamoDBClient.putBatch(DynamoDBClient.java:186)
>         at org.apache.hadoop.dynamodb.write.AbstractDynamoDBRecordWriter.write(AbstractDynamoDBRecordWriter.java:108)
>         at org.apache.hadoop.hive.dynamodb.write.HiveDynamoDBRecordWriter.write(HiveDynamoDBRecordWriter.java:42)
>         at org.apache.hadoop.hive.ql.exec.FileSinkOperator.process(FileSinkOperator.java:762)
>         at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:897)
>         at org.apache.hadoop.hive.ql.exec.SelectOperator.process(SelectOperator.java:95)
>         at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:897)
>         at org.apache.hadoop.hive.ql.exec.GroupByOperator.forward(GroupByOperator.java:1047)
>         at org.apache.hadoop.hive.ql.exec.GroupByOperator.processAggr(GroupByOperator.java:847)
>         at org.apache.hadoop.hive.ql.exec.GroupByOperator.processKey(GroupByOperator.java:721)
>         at org.apache.hadoop.hive.ql.exec.GroupByOperator.process(GroupByOperator.java:787)
>         ... 18 more
> ]

A. I would appreciate if the exception will be thrown immediately and not after an hour or more of expensive calculations.
B. The exception should be more readable, not `NullPointerException` from `org.apache.hadoop.dynamodb.DynamoDBUtil.getItemSizeBytes`.

Thanks,
Doron Grinzaig

**Comment by JunyangLi** [comment]
Fixed in PR - [Fix exception thrown for bad mapping #104](https://github.com/awslabs/emr-dynamodb-connector/pull/104)
