### ISSUE TITLE
List coming as NULL even when used with DynamoDBListStorageHandler

### ISSUE THREAD

**Issue by paddy-analytic-nbcu** [awslabs/emr-dynamodb-connector#82]
As per issue 74 the issue of having NULL list data when mapped to an array is fixed, but it is still coming in as NULL

Steps Followed
-------------------------
dynamoDB table name testReco1
Items : 
2 items ( attributes  id ( primary)  and test) 
(a) id :abcd, test :cncn
(b) id:cncn , test: [    { "S" : "h" },    { "S" : "e" }  ] 
As can be seen second item has test as as List

Copied 2 of the jars to s3
-----------------------------------
copied emr-dynamodb-hive-4.7.0-SNAPSHOT-jar-with-dependencies.jar to s3://<ourbucket>/emr-dynamodb-hive-4.7.0-SNAPSHOT-jar-with-dependencies.jar
copied emr-dynamodb-hadoop-4.7.0-SNAPSHOT.jar to s3://<ourbucket>/emr-dynamodb-hadoop-4.7.0-SNAPSHOT.jar

Steps in Hive
-----------------
*hive> add jar s3://**<ourbucket>**/emr-dynamodb-hive-4.7.0-SNAPSHOT-jar-with-dependencies.jar;
Added [/mnt/tmp/b8892051-3dea-4fe9-88e0-536ddd2742af_resources/emr-dynamodb-hive-4.7.0-SNAPSHOT-jar-with-dependencies.jar] to class path
Added resources: [s3://**<ourbucket>**/emr-dynamodb-hive-4.7.0-SNAPSHOT-jar-with-dependencies.jar]
hive> add jar s3://**<ourbucket>**/emr-dynamodb-hadoop-4.7.0-SNAPSHOT.jar
    > ;
Added [/mnt/tmp/b8892051-3dea-4fe9-88e0-536ddd2742af_resources/emr-dynamodb-hadoop-4.7.0-SNAPSHOT.jar] to class path
Added resources: [s3://**<ourbucket>**/emr-dynamodb-hadoop-4.7.0-SNAPSHOT.jar]
hive> drop table test;
OK
Time taken: 0.57 seconds
hive>
    > CREATE EXTERNAL TABLE test (id string, test **array<string>**) STORED BY **'org.apache.hadoop.hive.dynamodb.DynamoDBListStorageHandler'**
    > TBLPROPERTIES ("dynamodb.table.name" = "testReco1",
    > "dynamodb.column.mapping" = "id:id,test:test","dynamodb.region"="us-east-1");
WARNING: Configured write throughput of the dynamodb table testReco1 is less than the cluster map capacity. ClusterMapCapacity: 90 WriteThroughput: 5
WARNING: Writes to this table might result in a write outage on the table.
OK
Time taken: 1.19 seconds
hive> select * from test;
OK
abcd    NULL
cncn    NULL
Time taken: 1.546 seconds, Fetched: 2 row(s)
**-- Now create with test as just string **
hive> drop table test;
OK
Time taken: 0.044 seconds

hive> CREATE EXTERNAL TABLE test (id string, **test string**) STORED BY 'org.apache.hadoop.hive.dynamodb.DynamoDBListStorageHandler'
    > TBLPROPERTIES ("dynamodb.table.name" = "testReco1",
    > "dynamodb.column.mapping" = "id:id,test:test","dynamodb.region"="us-east-1");
OK
Time taken: 0.118 seconds
hive> select * from test;
OK
abcd    hh
cncn    NULL
Time taken: 0.184 seconds, Fetched: 2 row(s)

**Comment by umehrot2** [comment]
We tried it out, and it seems like this is broken. EMR will be taking a look at it internally, meanwhile if you are able to do a PR to fix this, feel free to go ahead.

**Comment by akumarb2010** [comment]
We are still getting list values as NULL's . Is this issue fixed now?

To debug this issue, it will be great, if we have few test cases with actual data sets. Is it possible to run Dynamo DB in embedded mode? Or is there any sample test case for data deserialization tests?

**Comment by JunyangLi** [comment]
Fixed by [Fix parsing logic for List type #107](https://github.com/awslabs/emr-dynamodb-connector/pull/107)
