### ISSUE TITLE
Support for on-demand capacity

### ISSUE THREAD

**Issue by perezpaya** [awslabs/emr-dynamodb-connector#86]
I've been trying to export DynamoDB from HiveSQL.

Using a simple Hive Script `select * from tableName` I encounter a read capacity error. The capacity calculation of the connector is made by using a percentage.

This script works great when the DynamoDB table is set on managed capacity mode. But when switched to on-demand error I encounter the Capacity error.

Could you enable a configuration setting that allows to use a table con on-demand capacity and that uses the maximum throughput the EMR Cluster will use?

Thanks you

**Comment by perezpaya** [comment]
#85

**Comment by feichashao** [comment]
Could I know the current status of this issue? I see the PR #85 is closed but not merged.

My customer and I are encountering this issue. A query to DynamoDB would fail with the below exception.
```

    > SELECT DISTINCT feature_class
    > FROM ddb_features_od
    > ORDER BY feature_class;

Status: Failed
Vertex failed, vertexName=Map 1, vertexId=vertex_1545727109987_0008_3_00, diagnostics=[Vertex vertex_1545727109987_0008_3_00 [Map 1] killed/failed due to:ROOT_INPUT_INIT_FAILURE, Vertex Input: ddb_features_od initializer failed, vertex=vertex_1545727109987_0008_3_00 [Map 1], java.lang.RuntimeException: Read throughput should not be less than 1. Read throughput percent: 0.0

```

**Comment by feichashao** [comment]
Also, the exception thrown is somehow misleading.

https://github.com/awslabs/emr-dynamodb-connector/blob/880145c5ad819ee83d1c96e108b1ee7b632d08b2/emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/read/AbstractDynamoDBInputFormat.java#L66

The value maxReadThroughputAllocated is read from dynamodb.throughput.read, which is not a 'percent'.

**Comment by anandhs** [comment]
+1, we have been waiting for this feature to be released too.

**Comment by taklwu** [comment]
https://github.com/awslabs/emr-dynamodb-connector/pull/88 has been merged as https://github.com/awslabs/emr-dynamodb-connector/commit/dca6c7547c446e33aff25da7fdf7d15c10aef516, so resolving this issue as well.
