### ISSUE TITLE
Support GSI as query condition in Hive

### ISSUE THREAD

**Issue by feichashao** [awslabs/emr-dynamodb-connector#87]
When we perform a query in Hive, like
``
Hive > SELECT * FROM ddb_table WHERE secondary_index="something";
``
It performs a scan() operation on the whole table, which lower the speed and make extra cost. My expected behavior is to perform query() operation on the table for GSI.

In getQueryFilter(), the only thing to determine whether it should be a query solely depend on the result from client.describeTable(conf.get(DynamoDBConstants.TABLE_NAME)).getKeySchema(). The getKeySchema() call only return the primary key and sort key, without the knowledge of GSI.

https://github.com/awslabs/emr-dynamodb-connector/blob/880145c5ad819ee83d1c96e108b1ee7b632d08b2/emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/read/HiveDynamoDBInputFormat.java#L126

I think we take advantage of the GSI information, before decide whether a scan or query should be applied.

One blocker I can think about is the attribute projection. If it is an "all projection", there should be no problem. 

Any suggestion?

**Comment by taklwu** [comment]
can you provide a bit more information about how you setup the table `ddb_table` with secondary index? that would help us to test your query. 

In addition, if you have any patch or idea, would you mind provide it as a PR (instead of issue)?
