### ISSUE TITLE
next release date ? 

### ISSUE THREAD

**Issue by anandhs** [awslabs/emr-dynamodb-connector#90]
We are looking to use the on demand dynamo changes that have been recently merged.  
Can I know the next release date since we would like to avoid a forked version if the release is sooner.

**Comment by devdeepak02** [comment]
Additionally need EMR version to switch to , where these changes be available.

**Comment by waynetaylor** [comment]
Would be good to get a confirmed release date.

**Comment by JunyangLi** [comment]
[The commit](https://github.com/awslabs/emr-dynamodb-connector/commit/dca6c7547c446e33aff25da7fdf7d15c10aef516) is merged into emr-dynamodb-connector version 4.8.0 which is available with EMR-5.22.0. 

EMR-5.22.0 was released on Apr/9/2019.

**Comment by taklwu** [comment]
resolving this issues as emr-5.22.0+ has all these improved features.
