### ISSUE TITLE
how to create emr-ddb.jar ??

### ISSUE THREAD

**Issue by rubyumeshc** [awslabs/emr-dynamodb-connector#93]
seems the packaging type mentioned in parent pom.xml is "pom"
how do we create the jar file which will contains the modules ex. emr-ddb.jar which will contain the hadoop, hive and tools modules

**Comment by bschell** [comment]
So pom.xml means the project uses the maven build tool.

To create the jars you can download the package
1. git clone https://github.com/awslabs/emr-dynamodb-connector.git

then run maven
2. mvn clean package

then the jars should be in the following "target" subdirectories:
/emr-dynamodb-connector/emr-dynamodb-hive/target/emr-dynamodb-hive-4.9.0-SNAPSHOT-jar-with-dependencies.jar
/emr-dynamodb-connector/emr-dynamodb-tools/target/emr-dynamodb-tools-4.9.0-SNAPSHOT.jar
/emr-dynamodb-connector/emr-dynamodb-hadoop/target/emr-dynamodb-hadoop-4.9.0-SNAPSHOT.jar

**Comment by rubyumeshc** [comment]
Hi yes i was able to generate the separate jars but my issue is, i want to create a single jar instead of 3 separate jars which will contain all of above modules

**Comment by foscraig** [comment]
You'll have to create your own uberjar and there are sources on the internet for doing that. Resolving.
