### ISSUE TITLE
Rate limiter returns batchsize of 1 after a segment completes

### ISSUE THREAD

**Issue by martindam** [awslabs/emr-dynamodb-connector#94]
When scanning a table with the Spark connector, the rate limiter breaks after it finishes its first segment and only returns RequestLimits with a batch size of 1 even though there are plenty of tokens left in the rate limiter. I believe this happens because the estimated item size goes to infinity when it receives an empty batch (which happens when the segment completes). This means that when it tries to estimate the number of items to fetch that always come out as 0 (which is rounded up to 1). 

The logs:
report: permitted=25.0, consumed=128.5, items=3326, avg from= 0.0 to 94.94936861094409
report: permitted=25.0, consumed=0.5, items=0, avg from= 94.94936861094409 to Infinity
report: permitted=25.0, consumed=0.5, items=1, avg from= Infinity to Infinity

**Comment by martindam** [comment]
Submitted PR: https://github.com/awslabs/emr-dynamodb-connector/pull/95

**Comment by taklwu** [comment]
closed because #95 committed
