### ISSUE TITLE
test fails while building jar using command mvn clean install

### ISSUE THREAD

**Issue by rubyumeshc** [awslabs/emr-dynamodb-connector#98]
testWithMultipleThreads(org.apache.hadoop.dynamodb.read.PageResultMultiplexerTest)  Time elapsed: 100.006 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 100000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1284)
	at java.lang.Thread.join(Thread.java:1358)
	at org.apache.hadoop.dynamodb.read.PageResultMultiplexerTest.testWithMultipleThreads(PageResultMultiplexerTest.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:748)

Running org.apache.hadoop.dynamodb.split.DynamoDBSplitGeneratorTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.052 sec

**Comment by rubyumeshc** [comment]
Results :

Tests in error: 
  testWithMultipleThreads(org.apache.hadoop.dynamodb.read.PageResultMultiplexerTest): test timed out after 100000 milliseconds

Tests run: 74, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] EMRDynamoDBConnector ............................... SUCCESS [  7.293 s]
[INFO] EMRDynamoDBHadoop .................................. FAILURE [04:25 min]
[INFO] EMRDynamoDBConnectorShims .......................... SKIPPED
[INFO] ShimsCommon ........................................ SKIPPED
[INFO] Hive1Shims ......................................... SKIPPED
[INFO] Hive2Shims ......................................... SKIPPED
[INFO] Hive1.2Shims ....................................... SKIPPED
[INFO] ShimsLoader ........................................ SKIPPED
[INFO] EMRDynamoDBHive .................................... SKIPPED
[INFO] EMRDynamoDBTools ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:32 min
[INFO] Finished at: 2019-05-04T17:59:07Z
[INFO] Final Memory: 32M/77M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project emr-dynamodb-hadoop: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/ec2-user/emr-dynamodb-connector/emr-dynamodb-hadoop/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command

**Comment by taklwu** [comment]
I tried with master branch today, it worked as below. (you cannot run `mvn test -Dtest=PageResultMultiplexerTest` from root, and tests of `shims` worked if you `cd` into the directory)

```
$ git log
commit c0201b79c6b72132ec37c580edde7be52ead1cd6
Author: You Li <youli@amazon.com>
Date:   Thu May 9 14:44:33 2019 +0800

    Auto scale in provisioned billing mode if user hasn't explicitly specify throughput

commit 113235f0f41ca8fb85725a1ee73971614c6b7330
Author: Hernan Vivani <vivanih@amazon.com>
Date:   Mon May 6 16:02:33 2019 +0000

    Prepare for 4.10.0 development

commit 36ce669d052b3cc33d2ee1a993619ec439aa2052
```

* build and run all tests 
```
$ mvn clean install
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] EMRDynamoDBConnector ............................... SUCCESS [  0.926 s]
[INFO] EMRDynamoDBHadoop .................................. SUCCESS [02:24 min]
[INFO] EMRDynamoDBConnectorShims .......................... SUCCESS [  0.038 s]
[INFO] ShimsCommon ........................................ SUCCESS [  2.755 s]
[INFO] Hive1Shims ......................................... SUCCESS [  2.215 s]
[INFO] Hive2Shims ......................................... SUCCESS [  0.741 s]
[INFO] Hive1.2Shims ....................................... SUCCESS [  0.772 s]
[INFO] ShimsLoader ........................................ SUCCESS [  0.366 s]
[INFO] EMRDynamoDBHive .................................... SUCCESS [  5.321 s]
[INFO] EMRDynamoDBTools ................................... SUCCESS [  3.040 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:41 min
[INFO] Finished at: 2019-05-09T10:08:59-07:00
[INFO] Final Memory: 85M/694M
[INFO] ------------------------------------------------------------------------
```

* only run `PageResultMultiplexerTest`

```
$ cd emr-dynamodb-hadoop/
$ mvn test -Dtest=PageResultMultiplexerTest

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.apache.hadoop.dynamodb.read.PageResultMultiplexerTest
log4j:WARN No appenders could be found for logger (org.apache.hadoop.dynamodb.preader.PageResultMultiplexer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
log4j:WARN No appenders could be found for logger (org.apache.hadoop.dynamodb.preader.PageResultMultiplexer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.934 sec

Results :

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.125 s
[INFO] Finished at: 2019-05-09T10:25:33-07:00
[INFO] Final Memory: 19M/312M
[INFO] ------------------------------------------------------------------------

```

**Comment by taklwu** [comment]
should not be an issue, resolve it for now.
