### ISSUE TITLE
Auto scaling is not working

### ISSUE THREAD

**Issue by youli9056** [awslabs/emr-dynamodb-connector#99]
Auto scaling in provisioned mode was working in previous version, but has been suppressed in [commit](https://github.com/awslabs/emr-dynamodb-connector/commit/dca6c7547c446e33aff25da7fdf7d15c10aef516#diff-9ac2a3ee2c139328fd4a0076417da17aL70). 

Related changes are: 
* When initial start in [DynamoDBStorageHandler](https://github.com/awslabs/emr-dynamodb-connector/blob/master/emr-dynamodb-hive/src/main/java/org/apache/hadoop/hive/dynamodb/DynamoDBStorageHandler.java#L171), jobConfig set READ/WRITE_THROUGHPUT 
*  Then in [IopsCalculator](https://github.com/awslabs/emr-dynamodb-connector/blob/master/emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/write/WriteIopsCalculator.java#L68) it takes precedence over latest dynamodb capacity.

**Comment by youli9056** [comment]
Thanks @taklwu ! How's the release schedule? Seems new changes won't be patched to existing release, so which EMR version I can expect this commit been released?

**Comment by taklwu** [comment]
I don't have ETA for the next release but at least I think it's emr-5.25.0+

for user who use this git to build their own jars, they can always replace these jars under `/usr/share/aws/emr/ddb/lib/` on a EMR cluster e.g. emr-5.20.0+ has the following.

```
$ ls -l /usr/share/aws/emr/ddb/lib/
total 180
lrwxrwxrwx 1 root root     29 May  9 23:24 emr-ddb-hadoop.jar -> emr-dynamodb-hadoop-4.7.0.jar
lrwxrwxrwx 1 root root     49 May  9 23:24 emr-ddb-hive.jar -> emr-dynamodb-hive-4.7.0-jar-with-dependencies.jar
-rw-r--r-- 1 root root 104732 Dec  7 19:41 emr-dynamodb-hadoop-4.7.0.jar
-rw-r--r-- 1 root root  76349 Dec  7 19:41 emr-dynamodb-hive-4.7.0-jar-with-dependencies.jar
```

**Comment by youli9056** [comment]
It's a bit tricky to replace it in prod env. Thanks for the info and looking forward to the release!
